# DO NOT TOUCH THIS
config-version: "1.2"

#Debug mode for extra debug logging
debug: false
#MYSQL Options for modules that require it
MySQL:
  #host use 127.0.0.1 or localhost for localhost
  host: localhost
  #name of the database you want the plugin to use (will create it if it doesn't exist)
  database: vorplexcoredb
  #username and password you want to plugin to use to access the MYSql database
  username: vorplexcore
  password: vorplexcore
  #the port must be an integer, default is 3306
  port: 3306
  #Extra arguments to use in the sql url
  extraArguments: ?useSSL=false

Plugin-Prefix: "<dark_purple>[<light_purple>Vorplex-Core<dark_purple>] "

#Server re-router module
#permission: vorplexcore.server.switch
VorplexServer:
  enabled: false
  #These are the servers defined in your bungeecord config (case sensitive)
  serverslist:
    - server1
    - server2
    - server3
  #the message to be sent to the player when sending them to a server. use %server% for the server name
  sendingtoservermessage: "&d&lSending you to %server%."

#auto restart module
#permission: vorplexcore.autorestart.admin
AutoRestart:
  enabled: true
  schedule:
    - "0 0 7 * * ?"
    - "0 0 19 * * ?"
  notify:
    bossBarCountdown:
      enabled: true
    sound:
      enabled: true
    chat:
      enabled: true
      periods:
        60: "<br><red>Auto Reboot in 1 minute<br>"
        30: "<br><red>Auto Reboot in 30 seconds<br>"
        20: "<br><red>Auto Reboot in 20 seconds<br>"
        10: "<br><red>Auto Reboot in 10 seconds<br>"
        5: "<br><red>Auto Reboot in 5 seconds<br>"
        4: "<br><red>Auto Reboot in 4 seconds<br>"
        3: "<br><red>Auto Reboot in 3 seconds<br>"
        2: "<br><red>Auto Reboot in 2 seconds<br>"
        1: "<br><red>Auto Reboot in 1 second<br>"
    title:
      enabled: true
      # Format: "[title] :: [subtitle] :: [fadeIn] [stay] [fadeOut]"
      # fadeIn, stay & fadeOut are in ticks
      periods:
        60: "<red>Restart soon :: <gray>1 minute left :: 15 40 15"
        30: "<red>Restart soon :: <gray>30 seconds left :: 15 40 15"
        20: "<red>Restart soon :: <gray>20 seconds left :: 15 40 15"
        10: "<red>Restart soon :: <gray>10 seconds left :: 15 40 15"
        5: "<red>Restart soon :: <gray>5 seconds left :: 15 40 1"
        4: "<red>Restart soon :: <gray>4 seconds left :: 1 40 1"
        3: "<red>Restart soon :: <gray>3 seconds left :: 1 40 1"
        2: "<red>Restart soon :: <gray>2 seconds left :: 1 40 1"
        1: "<red>Restart soon :: <gray>1 second left :: 1 40 1"

#auto-announcer module
AutoAnnouncer:
  enabled: true
  #pick announcement messages randomly
  Random: true
  #time between messages in seconds
  Interval: 120
  #uses mini message format
  Prefix: "<dark_purple>[<light_purple><b>Tip</b></light_purple>]</dark_purple>"
  Messages:
    - "<click:suggest_command:'That click event worked!'><hover:show_text:'This hover text is working<br>This next line is working'><white>This chat announcer is working!</white></hover></click>"
    - "<click:suggest_command:'That click event worked!'><hover:show_text:'This hover text is working<br>This next line is working'><white>This chat announcer is working!</white></hover></click>"
    - "<click:suggest_command:'That click event worked!'><hover:show_text:'This hover text is working<br>This next line is working'><white>This chat announcer is working!</white></hover></click>"
    - "<click:suggest_command:'That click event worked!'><hover:show_text:'This hover text is working<br>This next line is working'><white>This chat announcer is working!</white></hover></click>"
    - "<click:suggest_command:'That click event worked!'><hover:show_text:'This hover text is working<br>This next line is working'><white>This chat announcer is working!</white></hover></click>"


#auto item pickup module
AutoItemPickup:
  enabled: true
  InventoryFullSound: true
  AllowedItems:
    - SUGAR_CANE
    - WHEAT
    - PALE_HANGING_MOSS
    - CARROTS
    - BEETROOTS
    - PUMPKIN
    - MELON
    - NETHER_WART
    - COCOA
    - POTATOES
    - BAMBOO
    - TWISTING_VINES
    - TWISTING_VINES_PLANT
    - WEEPING_VINES
    - WEEPING_VINES_PLANT
    - CAVE_VINES
    - CAVE_VINES_PLANT
    - KELP
    - KELP_PLANT

#hub module (used for hub servers)
Hub:
  enabled: false
  #%player% will be replaced with the players name
  join-title-message: "&3&lVorplex &b&lNetwork:&7Welcome &c%player%&7. Enjoy your stay!:20:50:20"
  oxygen-helmet-enabled: true

#give player's the ability to change their donor rank prefix between all prefixes they have.
RankTitle:
  enabled: true
  #if the prefixes priority is higher than this it won't appear in the gui
  #this is also the priority that prefixes will be changed to when the player changes their prefix
  priority-to-add-prefixes: 45

#join messages module
JoinMessages:
  enabled: true
  #Will send join messages when a player un vanishes (requires Super Vanish or Premium vanish)
  SendOnUnVanish: true
  #set custom join messages per permission use %prefix% for prefix and %name% for player name. you can also use %title% for the player's title (this only works if titles are enabled!!)
  #higher messages in this list override
  permissionbasedjoinmessages:
    enabled: true
    messages:
      #permissions are as follows: vorplexcore.joinmessages.<permission defined here>
      permission1: "&6&lWelcome %title%%prefix%%name%!"
      permission2: "&6&ljoin message 2"
      permission3: "&6&ljoin message 3"
  #allows players to make their own join messages - permission: vorplexcore.customjoinmessages & vorplexcore.customjoinmessages.admin for clear command(Requires mysql connection)
  customjoinmessages:
    enabled: true
    #the maximum length for join messages (excludes color codes)(maximum 64)
    maxlength: 64

#leave messages module
LeaveMessages:
  enabled: true
  #Will send leave messages when a player vanishes (requires Super Vanish or Premium vanish)
  SendOnVanish: true
  #set custom leave messages per permission use %prefix% for prefix and %name% for player name. you can also use %title% for the player's title (this only works if titles are enabled!!)
  #higher messages in this list override
  permissionbasedleavemessages:
    enabled: true
    messages:
      #permissions are as follows: vorplexcore.leavemessages.<permission defined here>
      permission1: "&6&lGoodbye %title%%prefix%%name%!"
      permission2: "&6&lleave message 2"
      permission3: "&6&lleave message 3"
  #allows players to make their own leave messages - permission: vorplexcore.customleavemessages & vorplexcore.customleavemessages.admin for clear command(Requires mysql connection)
  customleavemessages:
    enabled: true
    #the maximum length for leave messages (excludes color codes)(maximum 64)
    maxlength: 64

#Gifts module - allows players to send each other items
#requires permissions: vorplexcore.gifts.send to be able to send gifts & vorplexcore.gifts.claim to be able to claim gifts
Gifts:
  enabled: true

#Buy command
buycommand:
  enabled: true
  # uses minimessage format
  message: "<b><gold>Store:</gold></b> <click:open_url:'https://store.vorplex.net'><u><aqua>https://store.vorplex.net</aqua></u></click>"







  