#MYSQL Options for modules that require it
MySQL:
  #host use 127.0.0.1 or localhost for localhost
  host: localhost
  #name of the database you want the plugin to use (will create it if it doesn't exist)
  database: vorplexcoredb
  #username and password you want to plugin to use to access the MYSql database
  username: vorplexcore
  password: vorplexcore
  #the port must be an integer, default is 3306
  port: 3306
  #Extra arguments to use in the sql url
  extraArguments: ?useSSL=false

Prefixes:
  plugin: "&5[&d&lvorplex-Core&5] "
  autorestart-module: "&5[&dvorplex-Restart&5] "

#/vote links module
VoteBookGUI:
  enabled: true
  #set the links that the book gui will send the player to here! (max 9 links, min 1 link)
  votelinks:
    1: "https://votelink1.com"
    2: "https://votelink2.com"
    3: "https://votelink3.com"
    4: "https://votelink4.com"
    5: "https://votelink5.com"

#vote rewards module (Gives rewards on each vote)
VoteRewards:
  enabled: true
  #commands to execute when a player votes. Use %player% for the player.
  commands:
    - "/command 1"
    - "/command 2"
    - "/command 3"
  #message to send to the player who votes use %votesite% for the vote site
  message: "&d&lThanks for voting on %votesite%!"
  #send a message to all players on the server that the player voted?
  broadcastvote: true
  #message to send to all players to when a player votes. Use %player% for player and %votesite% for the vote site.
  broadcast: "&d&l%player% has voted on %votesite% for some cool rewards"

#Server re-router module
#permission: vorplexcore.server.switch
VorplexServer:
  enabled: true
  #These are the servers defined in your bungeecord config (case sensitive)
  serverslist:
    - server1
    - server2
    - server3
  #the message to be sent to the player when sending them to a server. use %server% for the server name
  sendingtoservermessage: "&d&lSending you to %server%."

#auto restart module
#permission: vorplexcore.autorestart.admin
AutoRestart:
  enabled: true
  schedule:
    - "0 0 4 * * ?"
    - "0 15 16 * * ?"
  notify:
    # leave empty to disable sound
    sound: "UI_BUTTON_CLICK"
    chat:
      enabled: true
      periods:
        60: "§7[§eServer§7] Auto Reboot in §c1 minute"
        30: "§7[§eServer§7] Auto Reboot in §c30 seconds"
        5: "§7[§eServer§7] Auto Reboot in §c5 seconds"
        4: "§7[§eServer§7] Auto Reboot in §c4 seconds"
        3: "§7[§eServer§7] Auto Reboot in §c3 seconds"
        2: "§7[§eServer§7] Auto Reboot in §c2 seconds"
        1: "§7[§eServer§7] Auto Reboot in §c1 second"
    title:
      enabled: true
      # Format: "[title] :: [subtitle] :: [fadeIn] [stay] [fadeOut]"
      # fadeIn, stay & fadeOut are in ticks
      periods:
        60: "§cRestart soon :: §71 minute left :: 40 40 40"
        30: "§cRestart soon :: §730 seconds left :: 40 40 40"
        5: "§cRestart soon :: §75 seconds left :: 15 40 1"
        4: "§cRestart soon :: §74 seconds left :: 1 40 1"
        3: "§cRestart soon :: §73 seconds left :: 1 40 1"
        2: "§cRestart soon :: §72 seconds left :: 1 40 1"
        1: "§cRestart soon :: §71 second left :: 1 40 1"

#auto-announcer module
Announcer:
  enabled: true
  Random: true
  Interval: 60
  NumberOfMessages: 5
  Prefix: "&5[&d&lTip&5]"
  Messages:
    1:
      text: " &fThis chat announcer is working!"
      clickevent:
        action: "SUGGEST_COMMAND"
        value: "That click event worked!"
      hoverevent:
        action: "SHOW_TEXT"
        value: "&fThis hover text is working!\n&fThis next line is working"
    2:
      text: " &fThis chat announcer is working!"
      clickevent:
        action: "SUGGEST_COMMAND"
        value: "That click event worked!"
      hoverevent:
        action: "SHOW_TEXT"
        value: "&fThis hover text is working!\n&fThis next line is working"
    3:
      text: " &fThis chat announcer is working!"
      clickevent:
        action: "SUGGEST_COMMAND"
        value: "That click event worked!"
      hoverevent:
        action: "SHOW_TEXT"
        value: "&fThis hover text is working!\n &fThis next line is working"
    4:
      text: " &fThis chat announcer is working!"
      clickevent:
        action: "SUGGEST_COMMAND"
        value: "That click event worked!"
      hoverevent:
        action: "SHOW_TEXT"
        value: "&fThis hover text is working!\n&fThis next line is working"
    5:
      text: " &fThis chat announcer is working!"
      clickevent:
        action: "SUGGEST_COMMAND"
        value: "That click event worked!"
      hoverevent:
        action: "SHOW_TEXT"
        value: "&fThis hover text is working!\n&fThis next line is working"

#hub module (used for hub servers)
Hub:
  enabled: true
  #%player% will be replaced with the players name
  join-title-message: "&3&lVorplex &b&lNetwork:&7Welcome &c%player%&7. Enjoy your stay!:20:50:20"
  oxygen-helmet-enabled: true

#give player's the ability to change their donor rank prefix between all prefixes they have.
RankTitle:
  enabled: true
  #if the prefixes priority is higher than this it won't appear in the gui
  #this is also the priority that prefixes will be changed to when the player changes their prefix
  priority-to-add-prefixes: 45


#player Title module (allows players to have global titles - Requires MYSQL connection)
Titles:
  enabled: true
  #Permission for a title: vorplexcore.titles.<title id>
  #admin permissions:
  #vorplexcore.titles.create (/title create)
  #vorplexcore.titles.delete (/title delete)
  #vorplexcore.titles.help (/title help)
  #vorplexcore.titles.clear (/title clear)
  #vorplexcore.titles.set (/title set)


#join messages module
JoinMessages:
  enabled: true
  #Will send join messages when a player un vanishes (requires Super Vanish or Premium vanish)
  SendOnUnVanish: true
  #set custom join messages per permission use %prefix% for prefix and %name% for player name. you can also use %title% for the player's title (this only works if titles are enabled!!)
  #higher messages in this list override
  permissionbasedjoinmessages:
    enabled: true
    messages:
      #permissions are as follows: vorplexcore.joinmessages.<permission defined here>
      permission1: "&6&lWelcome %title%%prefix%%name%!"
      permission2: "&6&ljoin message 2"
      permission3: "&6&ljoin message 3"
  #allows players to make their own join messages - permission: vorplexcore.customjoinmessages & vorplexcore.customjoinmessages.admin for clear command(Requires mysql connection)
  customjoinmessages:
    enabled: true
    #the maximum length for join messages (excludes color codes)(maximum 64)
    maxlength: 64

#leave messages module
LeaveMessages:
  enabled: true
  #Will send leave messages when a player vanishes (requires Super Vanish or Premium vanish)
  SendOnVanish: true
  #set custom leave messages per permission use %prefix% for prefix and %name% for player name. you can also use %title% for the player's title (this only works if titles are enabled!!)
  #higher messages in this list override
  permissionbasedleavemessages:
    enabled: true
    messages:
      #permissions are as follows: vorplexcore.leavemessages.<permission defined here>
      permission1: "&6&lGoodbye %title%%prefix%%name%!"
      permission2: "&6&lleave message 2"
      permission3: "&6&lleave message 3"
  #allows players to make their own leave messages - permission: vorplexcore.customleavemessages & vorplexcore.customleavemessages.admin for clear command(Requires mysql connection)
  customleavemessages:
    enabled: true
    #the maximum length for leave messages (excludes color codes)(maximum 64)
    maxlength: 64

#Gifts module - allows players to send each other items
#requires permissions: vorplexcore.gifts.send to be able to send gifts & vorplexcore.gifts.claim to be able to claim gifts
Gifts:
  enabled: true

#Buy command
buycommand:
  enabled: true
  message: "&6&lStore: &b&nhttps://store.vorplex.net"

#Discord command
discordcommand:
  enabled: true
  message: "&6&discord: &b&nhttps://discord.vorplex.net"







  